### ISSUE TITLE
Translate to DataFrame

### ISSUE THREAD

**Issue by jordan-wirth** [redoverture/PACE#3]
The pickled data is in a sub-optimal structure for analysis when it comes out of a pickle. As of now, a pickle yields a dictionary of tuples, with timestamps as keys. Each timestamp entry contains a tuple of `(interval_devices, interval_total, interval_ssids)`. This structure ideally needs to be parsed into a Pandas DataFrame before we start analysis and plotting. There should be a function which takes a pickle and returns one or more DataFrame objects.

The Pickle structure:
- Timestamp: Starting timestamp for collected interval
    * Interval Devices: Set of MAC addresses (unique)
    * Interval Total: Total sniffed probes, non-unique, as an int
    * Interval SSIDS: Dictionary of SSID, count number of requests for an SSID over the interval

**Comment by jordan-wirth** [comment]
Some initial 3 frames of test data can be downloaded here: https://1drv.ms/u/s!AvyFX_h_PODtg_VSNCNDPLnedwAwEQ

@PsYcHo31327

**Comment by jordan-wirth** [comment]
New test data with new format! Be warned that a crash happened right after this on the Pi that I'm still troubleshooting, but a preliminary glance at the data looks okay up until this point.

https://1drv.ms/u/s!AvyFX_h_PODtg_Vf4FPHXMeRD8cvRA

@PsYcHo31327

**Comment by ghost** [comment]
Is the .Tar file format just for transmission or will we be expecting to record data in this format?

**Comment by jordan-wirth** [comment]
No, this is just for transmission.

**Comment by jordan-wirth** [comment]
Okay! Got this done in 8716aac172f8eeb00fd1ddc042a33ab7ce39a693 with the introduction of a couple functions to pace.analysis.read (simple_series and simple_pickle_jar). They only provide lengths (as in number of devices and SSIDs requested) but this is enough to start plotting and working with this data. I'm looking forward to finding any correlations between what we're measuring, to see if they're what I expect. We'll need to make at least two other DataFrames, for the more complex data, to work with in the future. One for the MAC Addresses, and one for the SSIDs. So, for now #3 stays open! But hey, we have data in a convenient format from pickles now!

![image](https://user-images.githubusercontent.com/20449792/55381048-11db9c00-54f0-11e9-9fd8-33e92b610e05.png)

**Comment by jordan-wirth** [comment]
Addressed fully in b3df22f37629a1f8f0879d28809d2ac11687ddae . Closing.
