### ISSUE TITLE
Recover from Monitor Mode

### ISSUE THREAD

**Issue by jordan-wirth** [redoverture/PACE#4]
While PACE successfully enters monitor mode on startup, it does not successfully take the adapter back into normal operating mode. The method in telemetry.state needs to be modified after research on taking hardware out of monitor mode on the Raspberry Pi.
`
    os.system('ifconfig ' + adapter + ' up')   < --- Incorrect
`

**Comment by benclermontt** [comment]
Why would the adapter need go into normal operating mode when it turns on? I thought we wanted it in monitor mode

**Comment by jordan-wirth** [comment]
This is for when the program exits. The adapter should return to normal operating mode once the program is finished running, when it catches SIGINT or some other condition.

**Comment by jordan-wirth** [comment]
Addressed in 91f3509160313e177367fc849c39cf0242622387. Closing.
